version: '3.5'
services:
  redis:
    container_name: redis
    image: redis:rc-buster
    ports:
      - "6379:6379"
    restart: on-failure
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
  postgres:
    container_name: postgres
    image: postgres:12.1
    env_file:
      - .env
    volumes:
      - .postgresdb/:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: on-failure

  chromedriver:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
