version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:12.1
    env_file:
      - .env
    volumes:
      - .postgresdb/:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: on-failure
    environment:
      - LC_ALL=C.UTF-8
      - VIRTUAL_HOST=postgres
      - VIRTUAL_PORT=5432
      
  redis:
    container_name: redis
    image: redis:rc-buster
    ports:
      - "6379:6379"
    restart: "always"
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis

  celery: 
    container_name: celery
    restart: "always"
    build: 
      context: .
      dockerfile: celery.dockerfile
    env_file: 
      - .env
    command: sh ./docker.celery.sh
    volumes:
      - .:/code
      - ./media:/code/media
    links:
      - postgres
      - redis
    depends_on: 
      - postgres
      - redis


  web:
    container_name: web
    build: .
    restart: "always"
    env_file: .env
    environment:
      - VIRTUAL_HOST=localhost, gale.inkidy.com, 144.91.118.81, 35.238.104.127
      - VIRTUAL_PORT=8000
      - TIMEOUT=300
      - HTTP_PORT=8000
      - STATS_PORT=8001
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - postgres
    depends_on:
      - "postgres"

      
networks:
  default:
    external:
      name: nginx-proxy